# Configuration file for the application
#server configuration
port: 666
auto-start: true #Automatically start the client processing on server startup
debug: true #Enable or disable debug mode
#database configuration
db_file: pos.db
db-r-host:
db_getremote: false
