# Configuration file for the application
#server configuration
port: 666
auto-start: true #Automatically start the client processing on server startup
debug: true #Enable or disable debug mode
#database configuration
db_host: localhost
db_port: 3306
db_username: pos
db_password: pos123
#logging configuration
dir: "logs\\" #Directory for log files